{
 "title": "SCD Cloud Accounting Dashboard",
 "tags": [ "cloud" ],
 "time": { "from": "2018-01-01T00:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "All_VOs", "label": "Activity", "query": "SELECT name FROM VOs" }
  ]
 },
 "panels": [
  {
   "title": "Elapsed time * Number of Processors (months) by VO and Month",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    {
     "format": "short",
     "label": "Elapsed time * Number of Processors (months)"
    }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  VO,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/2628000)\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Site='ral-cloud' and VO in ($All_VOs)\nGROUP BY 1,2\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Elapsed time * Number of Processors (months) by Site",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  Site,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/2628000)\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Site='ral-cloud' and VO in ($All_VOs)\nGROUP BY 1,2\nHAVING $__timeFilter(time)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Elapsed time * Number of Processors (months) by VO",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  Date as \"time\",\n  VO,\n  SUM((WallDuration*IF(CpuCount=0,1,CpuCount))/2628000)\nFROM VCombinedSummaries\nWHERE\n  $__timeFilter(Date) and Site='ral-cloud' and VO in ($All_VOs)\nGROUP BY 1,2\nHAVING $__timeFilter(time)\nORDER BY Date"
    }
   ]
  }
 ]
}